IRST with normal index + wp stat pickle file
castorini/pyserini pull request #1116
Opened 2022-04-11 19:25 UTC by stephaniewhoo

+ update irst with normal index + wp stat pickle file

2022-04-11 19:29 UTC, stephaniewhoo commented
Doc and doc seg are still WIP. Passage is ready.

2022-04-11 22:11 UTC, lintool commented on docs/experiments-msmarco-irst.md
> +  --tran-path irst_test/ibm_model_1_bert_tok_20211117/ \
How about we just name it `--translation-model`?

2022-04-11 22:14 UTC, lintool commented on docs/experiments-msmarco-irst.md
> +For MSMARCO DOC, each MS MARCO document is first segmented into passages, each passage is treated as a unit of indexing.
For MS MARCO doc, each document is...

2022-04-11 22:14 UTC, lintool commented on docs/experiments-msmarco-irst.md
> +For MSMARCO DOC, each MS MARCO document is first segmented into passages, each passage is treated as a unit of indexing.
For MS MARCO doc, each document is...

2022-04-11 22:15 UTC, lintool commented on docs/experiments-msmarco-irst.md
> +Download pretrained IBM models. Please note that we did not have time to train a new IBM model on MSMARCO DOC data, we used the trained MSMARCO Passage IBM Model1 instead.
"pretrained" is confusing in this context.

I've called it "already trained" instead... otherwise, it gets confused with BERT pretraining, right?

2022-04-11 22:15 UTC, lintool commented on docs/experiments-msmarco-irst.md
> +Download pretrained IBM models. Please note that we did not have time to train a new IBM model on MSMARCO DOC data, we used the trained MSMARCO Passage IBM Model1 instead.
"pretrained" is confusing in this context.

I've called it "already trained" instead... otherwise, it gets confused with BERT pretraining, right?

2022-04-15 01:21 UTC, lintool requested changes

2022-04-15 19:13 UTC, lintool approved these changes

2022-04-15 19:14 UTC, merged