Updated script to run with the SpacyNER tagger and REL linker
castorini/pyserini pull request #1226
Opened 2022-06-28 17:17 UTC by gsgoncalves

Refactored the EL script to support the updated REL code.
I followed the author's suggestions for [creating a new Mention Detection pipeline](https://github.com/informagi/REL/blob/main/tutorials/02_E2E_Entity_Linking.md#replacing-the-mention-detection-module).
It assumes that REL is installed via pip from their repo [as instructed](https://github.com/informagi/REL#option-2-installation-from-source-code).
Tested on a small portion of docs00.json (first 100 lines) that is generated while pre-processing the msmarco-passage for indexation with pyserini.
This approach, as the original code, is very RAM intensive. Batching and multi-processing can be added to improve the pipeline's performance.

2022-06-29 11:27 UTC, lintool commented
hey @arjenpdevries - can you get someone from your team to take a look at this?

2022-06-30 09:14 UTC, chriskamphuis commented on scripts/entity_linking.py
> +				left_ctxt = split_in_words(doc_text[:start_pos])
Maybe you can merge these three lines:

```
left_ctxt = " ".join(split_in_words(doc_text[:start_pos])[-100:])
```

same for right_ctxt

2022-06-30 09:15 UTC, chriskamphuis requested changes
It looks that the file now consists of a mixture of spaces and tabs, could you maybe make that consistent (spaces).

The PR looks good in terms of what you did :) Thank you!

2022-06-30 09:15 UTC, chriskamphuis commented on scripts/entity_linking.py
> +				left_ctxt = split_in_words(doc_text[:start_pos])
Maybe you can merge these three lines:

left_ctxt = " ".join(split_in_words(doc_text[:start_pos])[-100:])
same for right_ctxt

2022-07-02 10:02 UTC, chriskamphuis approved these changes

2022-07-10 13:54 UTC, merged

2022-07-10 13:54 UTC, lintool commented
@gsgoncalves thanks for your contribution!