ODQA Retrieval 2cr
castorini/pyserini pull request #1399
Opened 2022-12-27 19:16 UTC by ArthurChen189

Initial commit

2022-12-27 19:19 UTC, lintool commented
@ArthurChen189  👍 

Yup, this seems like the right direction.
I'm happy to just merge in stubs with BM25 baselines, and then add more conditions later.

Also add a direct link from the main README: https://github.com/castorini/pyserini/#two-click-reproductions

2022-12-28 23:07 UTC, ArthurChen189 commented
@lintool I think it is ready to be merged. Ground truths are also updated on both sides (paper, YAML).
Notes:
-  ODQA (https://castorini.github.io/pyserini/2cr/odqa.html) is added to the main README.md

2022-12-28 23:55 UTC, ArthurChen189 commented
Local and ORCA tests (html 2cr, _run all script_) passed. Ready for code review.

2022-12-29 00:06 UTC, lintool requested changes
lg, minor tweaks please.

2022-12-29 00:06 UTC, lintool commented on scripts/repro_matrix/utils.py
> +    return 0.0
How about we return the value that `os.system` returns? Corresponds to the exit status of the process...

2022-12-29 00:06 UTC, lintool commented on README.md
> ++ [ODQA](https://castorini.github.io/pyserini/2cr/odqa.html)
```suggestion
+ [Open-Domain Question Answering](https://castorini.github.io/pyserini/2cr/odqa.html)
```

2022-12-29 00:33 UTC, ArthurChen189 commented
Done!

2022-12-29 02:33 UTC, lintool approved these changes

2022-12-29 02:33 UTC, merged