Add gar-t5 topics to Pyserini's prebuilt topics
castorini/pyserini pull request #1408
Opened 2023-01-08 17:41 UTC by ArthurChen189

@ronakice

2023-01-08 18:46 UTC, ronakice approved these changes
LGTM!

2023-01-08 18:50 UTC, ronakice commented on pyserini/search/_base.py
> +    'gar-t5-dpr-trivia-test-all': JTopics.GART5_DPR_TRIVIA_TEST_ALL,
Actually, what about `gar-t5-answers` followed by the `nq-test` and so on, this is motivated by preserving the original naming schemes.

2023-01-10 22:04 UTC, ronakice requested changes
2 minor fixes and I'll merge.

2023-01-10 22:04 UTC, ronakice commented on docs/experiments-gar-t5.md
> -Once we have the tsv file, we can proceed to run search and evaluation
Perhaps include the first half of this in the end of the README file? Perhaps

## Method 2: Interacting with GAR-T5 Predictions

If you want to generate the pre-built topics yourself from the GAR-T5 Predictions, ... [enter whatever you have in the `Get the download...`

2023-01-10 22:04 UTC, ronakice commented on docs/experiments-gar-t5.md
> +  --topics <dpr-trivia, or nq>-test-gar-t5-<answers, titles, sentences, or all> \
no need the comma after dpr-trivia

2023-01-11 20:12 UTC, ronakice approved these changes
LGTM! Merging

2023-01-11 20:13 UTC, merged

2023-01-11 20:50 UTC, lintool commented
Sorry to chime in late, but @ArthurChen189 can we get some tests please? https://github.com/castorini/pyserini/blob/master/tests/test_load_qrels.py