Add AToMiC bm25 reproduction baselines
castorini/pyserini pull request #1536
Opened 2023-05-28 19:35 UTC by dlrudwo1269

Add prebuilt indexes for reproducing atomic bm25 baselines and a README showing how to reproduce the results.
(they are currently hosted on my personal huggingface space)

Also a small change in the query iterator to work with `jsonl` files

Note:
- need to update links to the indexes once they are moved to the `rgw.cs.uwaterloo.ca` server
- also a related PR adding the topics and qrels files https://github.com/castorini/anserini-tools/pull/51

2023-05-31 16:20 UTC, justram requested changes
The numbers are matched, but we need to address a few issues for the experiments md.

2023-05-31 16:20 UTC, justram commented on docs/experiments-atomic-bm25.md
> +If you have a dev installation of `pyserini`, the required files are located under `pyserini/tools/topics-and-qrels/`. Otherwise, you can download them at [this repository](https://huggingface.co/spa
Maybe add a few lines for explicit data prep, s.t. we can copy/paste the commands easily and check the results.

For example:
```bash
export DATA_DIR="https://huggingface.co/spaces/dlrudwo1269/AToMiC_bm25_files/resolve/main"

mkdir topics
wget ${DATA_DIR}/topics/validation.text.search.jsonl -P topics
wget ...

mkdir qrels
...
```

2023-06-01 02:02 UTC, dlrudwo1269 commented on docs/experiments-atomic-bm25.md
> +  --index lucene-index.atomic.image.{setting} \
My bad.. thought this would be the name of the actual file

2023-06-05 15:28 UTC, justram approved these changes

2023-06-05 15:31 UTC, merged