Reproducing experiment results for MS-MARCO passage and document ranking
castorini/pyserini pull request #1570
Opened 2023-07-14 20:28 UTC by pratyushpal

Environment Details: 
+ MacBook Pro Apple M2, 16GB RAM, Ventura 13.3 
+ Apache Maven 3.9.2
+ Java version: 20.0.1
+ Python 3.10.9

Issues:

+ pip install pyserini gave me a problem. nmslib wasn't installed. Similar to this issue  [#1551](https://github.com/castorini/pyserini/issues/1551).
+ I used the command below to resolve the error: 
`CFLAGS="-mavx -DWARN(a)=(a)" pip install nmslib`
and then just installed the remaining using `pip install pyserini` again.

2023-07-16 16:01 UTC, lintool requested changes
Should be a pyserini commit, not an anserini commit.

Yes, I noticed that @zoehahaha has a wrong URL, but I'll circle back and fix that later.

2023-07-17 21:11 UTC, pratyushpal commented
Updated URLs to point to a pyserini commit

2023-07-19 12:20 UTC, lintool approved these changes

2023-07-19 12:20 UTC, merged

2023-07-26 13:41 UTC, labaran1 commented
Getting the same error here and the solutions found online are not working.
MacBook Pro Apple M1, 8GB RAM, Ventura 13.4.1
Apache Maven 3.9.3
Java version: 20.0.1
Python 3.11.3

2023-07-27 09:25 UTC, lintool commented
@labaran1 - according to @pratyushpal , he got it working...

Can you provide the error traces?

2023-07-27 09:49 UTC, labaran1 commented
> @labaran1 - according to @pratyushpal , he got it working...
> 
> Can you provide the error traces?


805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/opt/homebrew/anaconda3/lib/python3.11/site-packages/numpy/core/include -I/opt/homebrew/anaconda3/include/python3.11 -c ./similarity_search/src/rangequery.cc -o build/temp.macosx-11.1-arm64-cpython-311/./similarity_search/src/rangequery.o -O3 -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"2.1.1\" -std=c++14 -fvisibility=hidden
      clang: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
      In file included from ./similarity_search/src/rangequery.cc:20:
      In file included from ./similarity_search/include/space.h:30:
      ./similarity_search/include/utils.h:53:12: warning: 'WARN' macro redefined [-Wmacro-redefined]
      #   define WARN(exp) (FILE_LINE_LINK "WARNING: " exp)
                 ^
      <command line>:2:9: note: previous definition is here
      #define WARN(a) (a)
              ^
      1 warning generated.
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -mavx -DWARN(a)=(a) -I./similarity_search/include -Itensorflow -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/opt/homebrew/anaconda3/lib/python3.11/site-packages/numpy/core/include -I/opt/homebrew/anaconda3/include/python3.11 -c ./similarity_search/src/searchoracle.cc -o build/temp.macosx-11.1-arm64-cpython-311/./similarity_search/src/searchoracle.o -O3 -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"2.1.1\" -std=c++14 -fvisibility=hidden
      clang: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
      In file included from ./similarity_search/src/searchoracle.cc:15:
      In file included from ./similarity_search/include/searchoracle.h:24:
      In file included from ./similarity_search/include/space.h:30:
      ./similarity_search/include/utils.h:53:12: warning: 'WARN' macro redefined [-Wmacro-redefined]
      #   define WARN(exp) (FILE_LINE_LINK "WARNING: " exp)
                 ^
      <command line>:2:9: note: previous definition is here
      #define WARN(a) (a)
              ^
      In file included from ./similarity_search/src/searchoracle.cc:15:
      In file included from ./similarity_search/include/searchoracle.h:26:
      ./similarity_search/include/params.h:256:23: warning: loop variable 's' creates a copy from type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char>>') [-Wrange-loop-construct]
          for (const string s: seen) other.seen.insert(s);
                            ^
      ./similarity_search/include/params.h:256:10: note: use reference type 'const std::string &' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') to prevent copying
          for (const string s: seen) other.seen.insert(s);
               ^~~~~~~~~~~~~~~
                            &
      2 warnings generated.
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -mavx -DWARN(a)=(a) -I./similarity_search/include -Itensorflow -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/opt/homebrew/anaconda3/lib/python3.11/site-packages/numpy/core/include -I/opt/homebrew/anaconda3/include/python3.11 -c ./similarity_search/src/space.cc -o build/temp.macosx-11.1-arm64-cpython-311/./similarity_search/src/space.o -O3 -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"2.1.1\" -std=c++14 -fvisibility=hidden
      clang: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
      In file included from ./similarity_search/src/space.cc:15:
      In file included from ./similarity_search/include/space.h:30:
      ./similarity_search/include/utils.h:53:12: warning: 'WARN' macro redefined [-Wmacro-redefined]
      #   define WARN(exp) (FILE_LINE_LINK "WARNING: " exp)
                 ^
      <command line>:2:9: note: previous definition is here
      #define WARN(a) (a)
              ^
      1 warning generated.
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -mavx -DWARN(a)=(a) -I./similarity_search/include -Itensorflow -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/private/var/folders/vk/j13m063s0fq_88h9yd2mdz840000gp/T/pip-install-cgsljote/nmslib_2d8df805bddf4510b7a5c3eb7df72b89/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include -I/opt/homebrew/anaconda3/lib/python3.11/site-packages/numpy/core/include -I/opt/homebrew/anaconda3/include/python3.11 -c ./similarity_search/src/space/space_ab_diverg.cc -o build/temp.macosx-11.1-arm64-cpython-311/./similarity_search/src/space/space_ab_diverg.o -O3 -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"2.1.1\" -std=c++14 -fvisibility=hidden
      clang: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
      In file included from ./similarity_search/src/space/space_ab_diverg.cc:20:
      In file included from ./similarity_search/include/space/space_ab_diverg.h:26:
      ./similarity_search/include/utils.h:53:12: warning: 'WARN' macro redefined [-Wmacro-redefined]
      #   define WARN(exp) (FILE_LINE_LINK "WARNING: " exp)
                 ^
      <command line>:2:9: note: previous definition is here
      #define WARN(a) (a)
              ^
      1 warning generated.
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/anaconda3/include -arch arm64 -mavx  [...]

2023-07-27 09:51 UTC, lintool commented
hrm. no idea off the top of my head here... you can try forcing install without the nmslib dependency, I suppose?

2023-07-27 11:31 UTC, labaran1 commented
> hrm. no idea off the top of my head here... you can try forcing install without the nmslib dependency, I suppose?

I tried " pip install pyserini  --no-dependencies nmslib"

I got 

Collecting pyserini
  Using cached pyserini-0.21.0-py3-none-any.whl (154.1 MB)
Collecting nmslib
  Using cached nmslib-2.1.1.tar.gz (188 kB)
  Preparing metadata (setup.py) ... done
Collecting Cython>=0.29.21 (from pyserini)
  Obtaining dependency information for Cython>=0.29.21 from https://files.pythonhosted.org/packages/f6/94/8d553dff3baf9cdd4b2481e59c2cfc8247c0c847170dd10574f81718d142/Cython-3.0.0-py2.py3-none-any.whl.metadata
  Using cached Cython-3.0.0-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting numpy>=1.18.1 (from pyserini)
  Obtaining dependency information for numpy>=1.18.1 from https://files.pythonhosted.org/packages/48/73/df07644e8fa1127a7985db70cf1d07123004e2dd7a3cf33e8b83297a775b/numpy-1.25.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.25.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting pandas>=1.4.0 (from pyserini)
  Obtaining dependency information for pandas>=1.4.0 from https://files.pythonhosted.org/packages/8f/bb/aea1fbeed5b474cb8634364718abe9030d7cc7a30bf51f40bd494bbc89a2/pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting pyjnius>=1.4.0 (from pyserini)
  Obtaining dependency information for pyjnius>=1.4.0 from https://files.pythonhosted.org/packages/d6/cf/503ddd8fdcc2f2e21c3750d4ecfb7851acda6796cf6df4ff95af51debb81/pyjnius-1.5.0-cp311-cp311-macosx_10_9_universal2.whl.metadata
  Using cached pyjnius-1.5.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (10 kB)
Collecting scikit-learn>=0.22.1 (from pyserini)
  Obtaining dependency information for scikit-learn>=0.22.1 from https://files.pythonhosted.org/packages/18/36/60b58b6199547b7b46be03e05508d053162fbce146639bfc65609fa49b23/scikit_learn-1.3.0-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Using cached scikit_learn-1.3.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting scipy>=1.4.1 (from pyserini)
  Obtaining dependency information for scipy>=1.4.1 from https://files.pythonhosted.org/packages/db/8d/6419a5a65a538791f49d52cd8f8883bd11b41df0c9d35f500c9650f1e0b7/scipy-1.11.1-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Using cached scipy-1.11.1-cp311-cp311-macosx_12_0_arm64.whl.metadata (100 kB)
Collecting tqdm (from pyserini)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting transformers>=4.6.0 (from pyserini)
  Obtaining dependency information for transformers>=4.6.0 from https://files.pythonhosted.org/packages/21/02/ae8e595f45b6c8edee07913892b3b41f5f5f273962ad98851dc6a564bbb9/transformers-4.31.0-py3-none-any.whl.metadata
  Using cached transformers-4.31.0-py3-none-any.whl.metadata (116 kB)
Collecting sentencepiece>=0.1.95 (from pyserini)
  Using cached sentencepiece-0.1.99-cp311-cp311-macosx_11_0_arm64.whl (1.2 MB)
Collecting onnxruntime>=1.8.1 (from pyserini)
  Obtaining dependency information for onnxruntime>=1.8.1 from https://files.pythonhosted.org/packages/17/2f/83f6ef69403624e74bc068f8674af34d3af44314a808adac267b2e379171/onnxruntime-1.15.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached onnxruntime-1.15.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.0 kB)
Collecting lightgbm>=3.3.2 (from pyserini)
  Using cached lightgbm-4.0.0-py3-none-macosx_13_0_arm64.whl
Collecting spacy>=3.2.1 (from pyserini)
  Obtaining dependency information for spacy>=3.2.1 from https://files.pythonhosted.org/packages/42/97/9e53df5890beea4430a868b102f1604619f4a21229fd0b6de3d6027f7892/spacy-3.6.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached spacy-3.6.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting pyyaml (from pyserini)
  Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/28/09/55f715ddbf95a054b764b547f617e22f1d5e45d83905660e9a088078fe67/PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting pybind11<2.6.2 (from nmslib)
  Using cached pybind11-2.6.1-py2.py3-none-any.whl (188 kB)
Collecting psutil (from nmslib)
  Using cached psutil-5.9.5-cp38-abi3-macosx_11_0_arm64.whl (246 kB)
Collecting coloredlogs (from onnxruntime>=1.8.1->pyserini)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers (from onnxruntime>=1.8.1->pyserini)
  Obtaining dependency information for flatbuffers from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting packaging (from onnxruntime>=1.8.1->pyserini)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting protobuf (from onnxruntime>=1.8.1->pyserini)
  Obtaining dependency information for protobuf from https://files.pythonhosted.org/packages/cb/d3/a164038605494d49acc4f9cda1c0bc200b96382c53edd561387263bb181d/protobuf-4.23.4-cp37-abi3-macosx_10_9_universal2.whl.metadata
  Using cached protobuf-4.23.4-cp37-abi3-macosx_10_9_universal2.whl.metadata (540 bytes)
Collecting sympy (from onnxruntime>=1.8.1->pyserini)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting python-dateutil>=2.8.2 (from pandas>=1.4.0->pyserini)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas>=1.4.0->pyserini)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas>=1.4.0->pyserini)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting joblib>=1.1.1 (from scikit-learn>=0.22.1->pyserini)
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/28/08/9dcdaa5aac4634e4c23af26d92121f7ce445c630efa0d3037881ae2407fb/joblib-1.3.1-py3-none-any.whl.metadata
  Using cached joblib-1.3.1-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.22.1->pyserini)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Using cached threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy>=3.2.1->pyserini)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy>=3.2.1->pyserini)
  Using cached spacy_loggers-1.0.4-py3-none-any.whl (11 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy>=3.2.1->pyserini)
  Using cached murmurhash-1.0.9-cp311-cp311-macosx_11_0_arm64.whl (18 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy>=3.2.1->pyserini)
  Using cached cymem-2.0.7-cp311-cp311-macosx_11_0_arm64.whl (30 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy>=3.2.1->pyserini)
  Using cached preshed-3.0.8-cp311-cp311-macosx_11_0_arm64.whl (98 kB)
Collecting thinc<8.2.0,>=8.1.8 (from spacy>=3.2.1->pyserini)
  Using cached thinc-8.1.10-cp311-cp311-macosx_11_0_arm64.whl (770 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy>=3.2.1->pyserini)
  Obtaining dependency information for wasabi<1.2.0,>=0.9.1 from https://files.pythonhosted.org/packages/8f/69/26cbf0bad11703241cb84d5324d868097f7a8faf2f1888354dac8883f3fc/wasabi-1.1.2-py3-none-any.whl.metadata
  Using cached wasabi-1.1.2-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy>=3.2.1->pyserini)
  Obtaining dependency information for srsly<3.0.0,>=2.4.3 from https://files.pythonhosted.org/packages/24/ec/6002a35662fa0a846c26a08ce14b13a040cddf2bb86cb9d4c03b84134eec/srsly-2.4.7-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached srsly-2.4.7-cp311-cp311-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy>=3.2.1->pyserini)
  Obtaining dependenc [...]

2023-07-27 11:34 UTC, lintool commented
Error trace shows that it's still trying to build nmslib.

2023-07-27 11:35 UTC, labaran1 commented
> Error trace shows that it's still trying to build nmslib.

Yh can't be ignored. It's a required package