Add OpenAI text-embedding-ada-002 API-based encoding
castorini/pyserini pull request #1622
Opened 2023-09-06 00:49 UTC by jasper-xian

2023-09-06 00:55 UTC, lintool commented
If we're going to strictly stick to camel case naming conventions, then `OpenAI` should be `OpenAi`... but that just looks ugly to me...

2023-09-06 15:18 UTC, ronakice requested changes
Just this change for now!

2023-09-06 15:18 UTC, ronakice commented on pyserini/encode/__main__.py
> +                embedding_writer.write(batch_info, args.input.fields)
A lot of this code is duplicated and can be condensed down to just the `int(args.encoder.rate_limit // (60 / OPENAI_API_RETRY_DELAY))` being different from `args.encoder.batch_size` so maybe clean that up?

2023-10-31 22:34 UTC, ronakice commented
@jasper-xian we should merge this?

2023-11-01 15:40 UTC, jasper-xian commented
yeah this should be good to merge @ronakice

2023-11-03 02:22 UTC, ronakice approved these changes
LGTM! Merging

2023-11-03 02:23 UTC, merged

2023-11-03 09:04 UTC, lintool commented
@jasper-xian can you send a PR to add dependencies to `requirements.txt`?