Add Reproducion logs for pyserini
castorini/pyserini pull request #1739
Opened 2023-12-04 19:11 UTC by ljk423

#### Reproduction Log for start.md

**Date:** 2023-12-04

### Setup Details:
**Operating System** 

- Mac OS Monterey ver 12.2.1

**Software Environment**

- Python 3.10.13
- Java 11.0.13

**Hardware Environment**

- CPU: Apple M1
- RAM: 8GB
- GPU: Apple M1

**Success/Failure**

- Everything Worked

**Additional Note**

- For some reason, the import statement for CosDprDocumentEncoder in pyserini/encode/__init__.py was deleted, so I added it manually.
- During the indexing process in experiments-nfcorpus.md, a segmentation fault occurred occasionally on the Apple M1 chip. After debugging using faulthandler, it was confirmed to be a torch-related issue. The problem was resolved by uninstalling torch using conda remove and reinstalling it. It is suspected that there was a conflict with the existing installation of torch.

2023-12-06 15:40 UTC, ljk423 reviewed
Changed commit hash into main trunk's hash

2023-12-09 02:58 UTC, lintool commented
Please fix conflicts.

2023-12-09 16:25 UTC, ljk423 commented
I fixed the conflicts. Sorry for inconvenience.
Thanks

2023-12-09 18:01 UTC, lintool commented
There should only be diffs for the four repro files. You have a lot more extra files as part of this PR. Please fix.

2023-12-10 02:52 UTC, ljk423 commented
I apologize, Professor. I have just deleted/restored all the files that were recently added or modified. I apologize once again for any inconvenience this may have caused.

Thanks

2023-12-10 11:42 UTC, lintool commented on pyserini/encode/__init__.py
> -from ._cosdpr import CosDprEncoder, CosDprDocumentEncoder, CosDprQueryEncoder
Is this change needed? Please undo.

2023-12-10 22:07 UTC, lintool approved these changes

2023-12-10 22:08 UTC, lintool requested changes
You need to also remove `docs/collections/nfcorpus.zip`

2023-12-11 02:53 UTC, ljk423 commented
I just deleted the collections directory in docs
I'm really sorry for inconvenience

2023-12-11 12:06 UTC, merged