Integration of arctic embeddings with pyserini
castorini/pyserini pull request #1980
Opened 2024-09-09 13:50 UTC by UShivani3

2024-11-20 19:36 UTC, lintool requested changes
`add_md5.py` is empty... why?
You need another readme file for embed-m?

2024-11-20 19:52 UTC, lintool commented on pyserini/encode/_base.py
> +        df['text'] = df['text'].apply(lambda x: x.strip())
maybe let's not change this... because it might break something else?

2024-12-07 12:28 UTC, lintool requested changes
Also, remove `scripts/arctic/add_md5.py`

2024-12-07 12:28 UTC, lintool commented on docs/experiments-arctic.md
> +# Pyserini: Reproducing Arctic Results
Let's rename this file `experiments-msmarco-v2.1-arctic.md`

2024-12-07 12:28 UTC, lintool commented on pyserini/encode/_base.py
> +        df['text'] = df['text'].apply(lambda x: x.strip())
Yes, please revert this change.

2024-12-07 12:28 UTC, lintool commented on pyserini/encoded_query_info.py
> +    },
Let's remove this for now.

2024-12-07 12:28 UTC, lintool commented on pyserini/prebuilt_index_info.py
> +    "beir-v1.0.0-nq.arctic-embed-m-v1.5": {
Let's remove this for now.

2024-12-07 12:28 UTC, lintool commented on pyserini/resources/index-metadata/faiss-flat.msmarco-v2.1-doc.arctic-embed-l.20240824.README.md
> +# msmarco-v2.1-arctic-embed-l
We're missing a README for arctic-m?

2024-12-07 12:28 UTC, lintool commented on pyserini/util.py
> +        filename = re.sub(r'\?.*$', '', filename)
Please revert.

2024-12-07 12:28 UTC, lintool commented on scripts/arctic/temp.sh
> +mv ArguAna faiss-flat.beir-v1.0.0-arguana.arctic-embed-m-v1.5.20241031
I don't think you mean to check this in?

2024-12-07 23:26 UTC, UShivani3 commented
> `add_md5.py` is empty... why? You need another readme file for embed-m?

removed

2024-12-08 01:43 UTC, lintool approved these changes

2024-12-08 04:43 UTC, merged