Integration of dense embedding model Snowflake arctic-embed-m-v1.5
castorini/pyserini pull request #2001
Opened 2024-10-01 18:58 UTC by Stefan824

This update integrates the Snowflake arctic-embed-m-v1.5 dense embedding model into the Pyserini toolkit. A new class was developed to support the entire snowflake-series of models, offering a scalable foundation for future expansions, such as additional Snowflake embedding model integrations. This enhancement lays the groundwork for smoother integration of future models from the Snowflake series

2024-10-01 19:10 UTC, Stefan824 commented
If is linked to resolving issue https://github.com/castorini/pyserini/issues/1959

2024-10-01 20:14 UTC, lintool requested changes

2024-10-01 20:29 UTC, Stefan824 commented on pyserini/search/faiss/_searcher.py
> +class ArcticQueryEncoder(QueryEncoder):
Yeah that is how the current version of pyserini does for all query encoders. Shivani and I were talking about this too. Maybe we could make a separate issue on this matter?

2024-10-01 20:33 UTC, lintool commented on pyserini/search/faiss/_searcher.py
> +class ArcticQueryEncoder(QueryEncoder):
@MXueguang ping on this?

2024-10-14 15:47 UTC, lintool requested changes
lg, but can you please add test cases, like in: https://github.com/castorini/pyserini/blob/master/tests/test_encoder_model_dpr.py

So maybe test case for the document encoder first - add query encoder test cases when we merge in the BEIR regressions?

2024-10-15 19:12 UTC, lintool approved these changes

2024-10-15 19:12 UTC, merged