Replicated Pyserini: BM25 Baselines for MS MARCO Document + Passage Ranking
castorini/pyserini pull request #304
Opened 2021-01-08 19:24 UTC by KaiSun314

OS: Ubuntu 18.04.5 LTS
JDK: 11.0.9.1
Maven: 3.6.0

Successfully replicated results:

![Pyserini_MSMARCO_Passage](https://user-images.githubusercontent.com/28762332/104055640-1b159480-51bd-11eb-8587-15b26d5c80e4.png)
![Pyserini_MSMARCO_Document](https://user-images.githubusercontent.com/28762332/104055643-1d77ee80-51bd-11eb-9c44-9e34d56b6cfc.png)

2021-01-08 20:11 UTC, MXueguang approved these changes
sorry i didn't noticed the `anserini` in the url. see below as @lintool commented.

2021-01-08 20:36 UTC, lintool requested changes
Fix broken URL - both places?

2021-01-08 20:36 UTC, lintool commented on docs/experiments-msmarco-doc.md
> ++ Results replicated by [@KaiSun314](https://github.com/KaiSun314) on 2021-01-08 (commit [`0d0628f`](https://github.com/castorini/anserini/commit/0d0628f24fb3e764df94aaf240c496482250deed))
`anserini`? I think you mean `pyserini`?

2021-01-09 03:08 UTC, lintool approved these changes

2021-01-09 03:08 UTC, merged