Fold evaluation program into pyserini directly
castorini/pyserini pull request #311
Opened 2021-01-11 18:33 UTC by MXueguang

re https://github.com/castorini/pyserini/issues/310

2021-01-11 18:35 UTC, MXueguang commented
output example:
```
Downloading https://raw.githubusercontent.com/castorini/anserini-tools/master/scripts/msmarco/msmarco_doc_eval.py to /home/xueguang/.cache/pyserini/eval/msmarco_doc_eval.py...
/home/xueguang/.cache/pyserini/eval/msmarco_doc_eval.py already exists!
Skipping download.
Running command: ['python3', '/home/xueguang/.cache/pyserini/eval/msmarco_doc_eval.py', '--judgments', 'qrels.msmarco-doc.dev.txt', '--run', 'run.msmarco-doc.doc.txt']
Quantity of Documents ranked for each query is as expected. Evaluating
#####################
MRR @100: 0.2770296928568702
QueriesRanked: 5193
#####################

```

2021-01-12 17:30 UTC, lintool requested changes
Don't rename args... just pass to underlying eval program. So:

```
java -jar jtreceval-0.0.5-jar-with-dependencies.jar -m map -m P.30 qrels.robust04.txt run.robust04.txt
```
Becomes:

```
python -m pyserini.eval.trec_eval -m map -m P.30 qrels.robust04.txt run.robust04.txt
```

I think this means we'll be mixing `-arg` and `--arg`, but trying to rename the args will be even more confusing, I think...

2021-01-12 17:30 UTC, lintool commented on pyserini/eval/msmarco_doc_eval.py
> +cmd = ['python3', script_path, '--judgments', args.qrel, '--run', args.run]
I don't think we should try to parse and rename the args. Just pass unchanged to underlying eval script.

2021-01-12 20:06 UTC, lintool approved these changes
Pulled branch and verified. Works great!

2021-01-12 20:18 UTC, merged