script for hybird result externally
castorini/pyserini pull request #434
Opened 2021-03-17 16:50 UTC by MXueguang

script for hybrid results 
cc: @ronakice

2021-03-17 16:53 UTC, lintool requested changes
scripts should be named as verb phrases... i.e., "do this"

Maybe something like `compute_hybrid_results`? or `perform_hybrid_retrieval` or something along those lines?

2021-03-17 17:01 UTC, lintool commented
This is something that @ronakice requested? I'm missing the context here, in the sense that `-m search` already does hybrid?

2021-03-22 11:19 UTC, lintool approved these changes

2021-03-22 14:57 UTC, ronakice approved these changes
LGTM!

2021-03-22 15:27 UTC, merged