Add retrievers and models to demo
castorini/pyserini pull request #557
Opened 2021-05-12 04:44 UTC by saileshnankani

Solves https://github.com/castorini/pyserini/issues/548 (interactive retrieval demo). 

This PR adds support for `dense` and `hybrid` retrievers to the interactive demo through the `/retriever` command. 
For these retrievers, this PR adds support for 2 encoder models, `tct` and `ance`.

Also, with `tct`, there are 2 possible indices: (1) HNSW index i.e. and (2) brute-force index i.e. msmarco-passage-tct_colbert-bf. I used (1) in this PR.

2021-05-12 10:28 UTC, lintool commented
What happened here?

2021-05-12 10:32 UTC, MXueguang commented
@saileshnankani you closed the PR?

2021-05-12 14:11 UTC, saileshnankani commented
Yes, sorry I did but forgot to add comment before closing. I couldn't test the code in colab due to memory constraints as tct models is huge. I'm currently trying to test it in CC before reopening the PR.

2021-05-12 14:13 UTC, MXueguang commented
I see.
I'll do the CR once you finish the test.
The current design looks good to me.

2021-05-19 06:33 UTC, saileshnankani commented
I was able to test it in `tuna`.  Below is a sample output:

```
>>> /model tct
Attempting to initialize pre-built index msmarco-passage-tct_colbert-hnsw.
/tuna1/scratch/indexes/dindex-msmarco-passage-tct_colbert-hnsw-20210112-be7119.7e12ae728ea5f2ae6d1cfb88a8775ba8 already exists, skipping download.
Initializing msmarco-passage-tct_colbert-hnsw...
setting model = tct
>>> /mode dense
setting retriver = dense
>>> how many planets in solar system?
 1 70.07428 There are approximately 560,000,000,000 planets in outer space that scientists have discovered. In this solar system, there are eight planets. In this galaxy, there are likely between 50 billion and a trillion planets-or more. At this point, we can hardly guess.
 2 70.07053 Our solar system officially has eight planets and one star: the Sun. In order from the Sun out, the planets are: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.
 3 69.93992 We do not know how many planets there are in space. But the answer would be in the Billions or trillions. The International Astronomical Union (IAU) recognises eight planets in our solar system (from closest to sun to furthest); Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune.
>>> /mode hybrid
setting retriver = hybrid
>>> how many planets in solar system?
 1 71.51600 There are approximately 560,000,000,000 planets in outer space that scientists have discovered. In this solar system, there are eight planets. In this galaxy, there are likely between 50 billion and a trillion planets-or more. At this point, we can hardly guess.
 2 71.51226 Our solar system officially has eight planets and one star: the Sun. In order from the Sun out, the planets are: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.
 3 71.41823 solar system image by hugy from Fotolia.com. Drawing the solar system can be a fun project for kids to learn about our neighboring planets. The solar system is made up of eight planets, 162 moons, several dwarf planets (such as Pluto), comets, and many asteroids.Learning how to draw the solar system can provide a basic understanding of the size of the planets, their distance from the sun, and other information about astronomy.The solar system is easy to draw, and the project can be enjoyable for children or anybody interested in astronomy and our place in the universe.raw a large circle to represent the sun. The sun contains 99.8% of the mass in our solar system. That should give you a good indication of quite how large the sun is. Draw the sun using your original vertical line (the furthest to the left) as a guide.
```

2021-05-19 08:46 UTC, lintool requested changes
lg! Minor changes.

2021-05-19 08:46 UTC, lintool commented on pyserini/demo/msmarco.py
> +        print(
We use 120 width, so this can be on it's own line.

2021-05-19 08:46 UTC, lintool commented on pyserini/demo/msmarco.py
> +                print(f'specify model through /model before using dense retrieval')
Msg should be complete sentences, e.g., 'Specify model through /model before using dense retrieval.'
Same for others.

2021-05-19 18:14 UTC, MXueguang approved these changes
lgtm!

2021-05-19 18:53 UTC, lintool approved these changes

2021-05-19 18:54 UTC, merged